[package]
name = "sms-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
redis.workspace = true
serde_json.workspace = true
dotenvy.workspace = true
sms-core = { path = "../sms-core" }
