[package]
name = "sms-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
sms-core = { version = "0.1.0", path = "../sms-core" }
tokio.workspace = true
serde_json.workspace = true
redis.workspace = true
dotenvy = "0.15.7"
