[package]
name = "sms-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "macros"] }
thiserror = "2.0.12"
tokio.workspace = true
serde.workspace = true
